
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: gaPunyaNama
      POSTGRES_PASSWORD: masihGapunyaNama
      POSTGRES_DB: dbGapunyanama
    ports:
      - "5433:5432"
    volumes:
      - ./db_awal:/docker-entrypoint-initdb.d/

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  sijarta:
    build:
      context: .
      dockerfile: Dockerfile
    image: sijarta:commit_pertama
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://gaPunyaNama:masihGapunyaNama@db:5432/dbGapunyanama
      # Dibawah adalah prod build
      # DATABASE_URL: postgresql://SIJARTA_owner:DClI4XAv0WuY@ep-weathered-violet-a16j35xm.ap-southeast-1.aws.neon.tech/SIJARTA?sslmode=require
    depends_on:
      - db

# volumes:
#   db_data: nyalakan saat ingin database persistency